pipeline {
    agent any
    environment {
        JAVA_HOME = tool name: 'JDK17'
        PATH = "${env.JAVA_HOME}/bin:${env.PATH}"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                bat './gradlew.bat assembleDebug'
            }
        }
    }
}
